---
namespace: "labrats_work"
name: "modules_ansible"
version: 1.0.7
description: "Collection of ansible playbooks and roles"

authors:
  - "Thomas Pisula <tompisula@labrats.work>"

repository: "https://github.com/labrats-work/modules-ansible"
documentation: "https://github.com/labrats-work/modules-ansible/README.md"
homepage: "https://github.com/labrats-work/modules-ansible"
issues: "https://github.com/labrats-work/modules-ansible/issues"

readme: "README.md"
license: "GPL-3.0-or-later"

tags:
  - "linux"
  - "containers"
  - "kubernetes"
  - "haproxy"