---
# tasks file for systemd_haproxy

- name: Create User
  user:
    name: haproxy
    shell: /sbin/nologin

- name: Create directory if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: haproxy
    group: haproxy
    state: directory
    mode: 0750
  loop:
  - /etc/haproxy

- name: Update Apt Cache
  ansible.builtin.apt: 
    update_cache: yes

- name: Haproxy Package Installed
  ansible.builtin.package:
    name: 
      - haproxy
    state: present

- name: Copy http error files.
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/etc/haproxy/errors/"
    owner: haproxy
    group: haproxy
    mode: 0644
  with_fileglob:
    - haproxy/*.http

- name: Create empty haproxy.cfg file.
  become: yes
  ansible.builtin.copy:
    content: ""
    dest: /etc/haproxy/haproxy.cfg
    owner: haproxy
    group: haproxy
    mode: 0644

- name: Update haproxy.cfg.
  become: yes
  ansible.builtin.blockinfile:
    path: /etc/haproxy/haproxy.cfg
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: "{{ haproxy_config }}"

- name: Service Enabled
  ansible.builtin.service:
    name: haproxy
    enabled: yes
    state: started

- name: Service Restart
  ansible.builtin.service:
    name: haproxy
    state: restarted