- name: Check if Kubernetes is installed
  command: kubectl version --short
  register: kubectl_result
  ignore_errors: true

- name: Install if kubectl version rc is zero
  when: kubectl_result.rc == 1
  block:

    - name: Create empty config file.
      become: yes
      ansible.builtin.copy:
        content: ""
        dest: /root/kubeadm_join.yaml
        owner: root
        group: root
        mode: '0600'

    - name: Create yaml configs.
      become: yes
      ansible.builtin.blockinfile:
        path: /root/kubeadm_join.yaml
        marker: "# {mark} ANSIBLE MANAGED BLOCK {{ item.kind }}"
        block: |
          {{ item | to_nice_yaml(sort_keys=false) }}
          {%- if not ansible_loop.last %}
          ---
          {% endif %}
      no_log: true  
      loop: "{{ yaml_configs }}"
      loop_control:
        extended: true

    - name: Restart container runtime
      ansible.builtin.service:
        name: containerd
        state: restarted 

    - name: Run kubeadm init.
      ansible.builtin.shell: kubeadm join --config=/root/kubeadm_join.yaml | tee kubeadm_join.out