- name: Check if Kubernetes is installed
  command: kubectl version
  register: kubectl_result
  ignore_errors: true

- name: Install if kubectl version rc is zero
  when: kubectl_result.rc == 1
  block:

    - name: Copy discovery.conf for kubeadm init.
      ansible.builtin.template:
        src: "templates/discovery.conf.j2"
        dest: /root/discovery.conf
        owner: root
        group: root
        mode: '0600'

    - name: Default kubeadm join.
      ansible.builtin.command: kubeadm config print join-defaults
      register: kubeadm_config_print

    - name: Combine with user defined vars.
      ansible.builtin.copy:
        content: |-
          {{ dict|combine(changes)|to_nice_yaml }}
        dest: /root/kubeadm_join.yaml
        owner: root
        group: root
        mode: '0600'
      vars:
        dict: "{{ kubeadm_config_print.stdout|from_yaml }}"
        changes: "{{ kubeadm_join }}"

    - name: Restart container runtime
      ansible.builtin.service:
        name: containerd
        state: restarted 

    - name: Run kubeadm init.
      ansible.builtin.shell: kubeadm join --config=/root/kubeadm_join.yaml | tee kubeadm_join.out