
- name: Download flux installer script.
  ansible.builtin.command: 
    argv:
      - wget 
      - https://fluxcd.io/install.sh 
      - -O 
      - flux_install.sh
    creates: flux_install.sh

- name: Chmod flux installer script.
  ansible.builtin.file: 
    path: flux_install.sh
    owner: sysadmin
    group: sysadmin
    mode: '0700'

- name: Run flux installer script.
  ansible.builtin.command: 
    argv: 
     - ./flux_install.sh

- name: Run flux bootstrap.
  become: no
  ansible.builtin.shell: flux bootstrap github --owner={{ flux_init_owner }} --repository={{ flux_init_repo }} --path={{ flux_init_path }} --personal | tee fluxbootstrap.out
  environment: 
    GITHUB_TOKEN: "{{ flux_init_token }}"
