- name: Debug Worker Defaults
  ansible.builtin.debug: 
    var: worker_defaults
  when: kubernetes_debug

- name: Debug Worker Group
  ansible.builtin.debug: 
    var: worker_group
  when: kubernetes_debug

- name: Debug Worker
  ansible.builtin.debug: 
    var: worker
  when: kubernetes_debug

- name: Create Merged Dictionary
  ansible.builtin.set_fact: 
    kubernetes: "{{ worker_defaults | combine(worker_group) | combine(worker) }}"
    discovery: "{{ hostvars[master_node]['discovery'] }}"
   
- name: Debug Merged Dictionary
  ansible.builtin.debug: 
    var: kubernetes
  when: kubernetes_debug
  
- name: Copy discovery.conf for kubeadm init.
  ansible.builtin.template:
    src: "templates/discovery.conf.j2"
    dest: /root/discovery.conf
    owner: root
    group: root
    mode: '0600'

- name: Copy kubeadm_join.yaml for kubeadm join.
  ansible.builtin.template:
    src: "templates/kubeadm_join.yaml.j2"
    dest: /root/kubeadm_join.yaml
    owner: root
    group: root
    mode: '0600'

- name: Restart container runtime
  ansible.builtin.service:
    name: containerd
    state: restarted 

- name: Run kubeadm init.
  ansible.builtin.shell: kubeadm join --config=/root/kubeadm_join.yaml | tee kubeadm_join.out