- name: Ensure docker pre-requisites
  ansible.builtin.package:
    name: 
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present

- name: Setup keyring Rocky | CentOS
  ansible.builtin.shell: sudo dnf config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  when: ansible_facts['distribution'] == "Rocky" or ansible_facts['distribution'] == "CentOS"

- name: Setup keyring Ubuntu | Debian
  ansible.builtin.shell: |
    mkdir -p /usr/share/keyrings/
    rm /usr/share/keyrings/docker-archive-keyring.gpg
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    chmod a+r /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"

- name: Update packages Ubuntu | Debian
  ansible.builtin.apt: 
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"

- name: Ensure docker installed
  ansible.builtin.package:
    name: 
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin    
    state: present

- name: Update docker daemon config.
  ansible.builtin.template:
    src: "templates/daemon.j2"
    dest: /etc/docker/daemon.json
    owner: root
    group: root
    mode: '0770'

- name: Restart service docker - with daemon reload.
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: docker