---
# tasks file for docker

- name: Install Helm from Apt
  block:

    - ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/trusted.gpg.d/docker.gpg

    - ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update packages Ubuntu | Debian
      ansible.builtin.apt: 
        update_cache: yes

    - name: Ensure docker installed
      ansible.builtin.package:
        name: 
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin    
        state: present

    - name: Update docker daemon config.
      ansible.builtin.template:
        src: "templates/daemon.json.j2"
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0770'
      when: ansible.builtin.stat.mtime != ansible.builtin.stat.stat('/etc/docker/daemon.json').mtime

    - name: Restart service docker - with daemon reload.
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: docker
      when: ansible.builtin.stat.mtime != ansible.builtin.stat.stat('/etc/docker/daemon.json').mtime