---
# tasks file for docker

- name: Install Docker from Apt
  become: true
  block:
    - name: Check if packages are already installed
      ansible.builtin.apt: 
        list_packages:
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
      register: package_check
      failed_when: package_check.stdout == ""

    - name: Check if Docker service is running
      ansible.builtin.shell: systemctl is-active docker
      register: service_check
      failed_when: service_check.rc != 0

    - name: Install packages if not already installed
      ansible.builtin.apt: 
        update_cache: yes
      when: package_check.stdout == ""

    - ansible.builtin.package:
        name: 
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-compose-plugin
        state: latest
      when: package_check.stdout == ""

    - ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/trusted.gpg.d/docker.gpg

    - ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    - name: Update packages Ubuntu | Debian
      ansible.builtin.apt: 
        update_cache: yes
      when: package_check.stdout == ""

    - name: Update docker daemon config.
      ansible.builtin.template:
        src: "templates/daemon.json.j2"
        dest: /etc/docker/daemon.json
        owner: root
        group: root
        mode: '0770'
      when: service_check.rc != 0

    - name: Restart service docker - with daemon reload.
      ansible.builtin.systemd:
        state: restarted
        daemon_reload: yes
        name: docker
      when: service_check.rc != 0
