---
# tasks file for docker_prometheus
- name: Create User
  user:
    name: prometheus
    shell: /sbin/nologin

- name: Create directory if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
    state: directory
    mode: 0750
  loop:
  - /etc/prometheus

- name: Copy config
  ansible.builtin.copy:
    src:  files/prometheus.yml
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0644

- name: Create Prometheus Volume
  community.docker.docker_volume:
    driver: "local"
    name: prometheus-storage

- name: Create Prometheus Container
  community.docker.docker_container:
    name: prometheus
    state: started
    image: prom/prometheus:latest
    restart_policy: always
    etc_hosts: "{{ etc_hosts }}"
    ports:
      - '9090:9090'
    volumes:
      - '/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - 'prometheus-storage:/var/lib/prometheus'