---
# tasks file for docker_prometheus
- name: Create User
  user:
    name: prometheus
    shell: /sbin/nologin

- name: Create directory if it does not exist
  ansible.builtin.file:
    path: "{{ item }}"
    owner: prometheus
    group: prometheus
    state: directory
    mode: 0750
  loop:
  - /etc/prometheus

- name: Create empty config file.
  become: yes
  ansible.builtin.copy:
    content: ""
    dest: /etc/prometheus/prometheus.yml
    owner: prometheus
    group: prometheus
    mode: 0644

- name: Create yaml config.
  become: yes
  ansible.builtin.blockinfile:
    path: /etc/prometheus/prometheus.yml
    marker: "# {mark} ANSIBLE MANAGED BLOCK"
    block: "{{ prometheus_config | to_nice_yaml(sort_keys=false) }}"

- name: Create Prometheus Volume
  community.docker.docker_volume:
    driver: "local"
    name: prometheus-storage

- name: Create Prometheus Container
  community.docker.docker_container:
    name: prometheus
    state: started
    image: prom/prometheus:latest
    restart_policy: always
    etc_hosts: "{{ etc_hosts }}"
    network_mode: "{{ network_mode }}"
    ports:
      - '9090:9090'
    volumes:
      - '/etc/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml'
      - 'prometheus-storage:/var/lib/prometheus'