name: Update Ansible Galaxy Collection Version

on: 
  push:
      
jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2
      
      # Read the current version number from the galaxy.yml file
      - id: current_version
        shell: bash
        run: |
          echo "version=$(cat galaxy.yml | grep version | awk -F':' '{print $2}')" >> $GITHUB_OUTPUT
      
      # Increment the patch version number by one
      - id: patch_version
        if: github.ref == 'refs/heads/dev'
        run: |
          version="${{ steps.current_version.outputs.version }}"
          major=$(echo "$version" | awk -F'.' '{print $1}')
          minor=$(echo "$version" | awk -F'.' '{print $2}')
          patch=$(echo "$version" | awk -F'.' '{print $3}')
          new_patch=$((patch+1))
          new_version="$major.$minor.$new_patch"
          echo "Updating version to $new_version"
          sed -i "s/$version/$new_version/g" galaxy.yml
          echo "new_version=$new_version" >> $GITHUB_OUTPUT
      
      # Config git
      - run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"

      # Commit the changes
      - if: github.ref == 'refs/heads/dev'
        run: |
          git add galaxy.yml
          git commit -m "Update galaxy.yml version to ${{ steps.patch_version.outputs.new_version }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Tag if main    
      - if: github.ref == 'refs/heads/main'
        run: |
          git tag ${{ steps.current_version.outputs.version }}
          git push origin --tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}