name: Update Ansible Galaxy Collection Version

on: [push]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      # Check out the repository
      - uses: actions/checkout@v2
      
      # Read the current version number from the galaxy.yml file
      - run: cat galaxy.yml | grep version
        shell: bash
        id: current_version
      
      # Increment the patch version number by one
      - run: |
          version=$(echo "${{ steps.current_version.output }}" | awk -F':' '{print $2}')
          major=$(echo "$version" | awk -F'.' '{print $1}')
          minor=$(echo "$version" | awk -F'.' '{print $2}')
          patch=$(echo "$version" | awk -F'.' '{print $3}')
          new_patch=$((patch+1))
          new_version="$major.$minor.$new_patch"
          echo "Updating version to $new_version"
          sed -i "s/$version/$new_version/g" galaxy.yml
        shell: bash
      
      # Commit and push the changes to the repository
      - uses: actions/github-script@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            git config --local user.email "action@github.com"
            git config --local user.name "GitHub Action"
            git add galaxy.yml
            git commit -m "Update galaxy.yml version to $new_version"
            git push