- name: Setup keyring Ubuntu | Debian
  ansible.builtin.shell: |
    mkdir -p /usr/share/keyrings/
    rm /usr/share/keyrings/docker-archive-keyring.gpg
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    chmod a+r /usr/share/keyrings/docker-archive-keyring.gpg
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
  when: ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"

- name: Update packages Ubuntu | Debian
  ansible.builtin.apt: 
    update_cache: yes
  when: ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"

- name: Packages Installed
  ansible.builtin.package:
    name: containerd.io
    state: present

- name: Configure Service
  ansible.builtin.shell: |
    containerd config default > /etc/containerd/config.toml
    sed -i 's|SystemdCgroup = false|SystemdCgroup = true|g' /etc/containerd/config.toml

- name: Service Started
  service:
    name: containerd
    state: started
    enabled: yes