---
# tasks file for containerd

- name: Check if package is absent
  ansible.builtin.package:
    name: containerd.io
    state: absent
  check_mode: true
  register: package_check

- name: Install Containerd from Apt
  when: package_check is succeeded
  block:

    - ansible.builtin.apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
        keyring: /etc/apt/trusted.gpg.d/docker.gpg

    - ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/docker.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

    # - name: Setup keyring Ubuntu | Debian
    #   ansible.builtin.shell: |
    #     mkdir -p /usr/share/keyrings/
    #     rm /usr/share/keyrings/docker-archive-keyring.gpg
    #     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
    #     chmod a+r /usr/share/keyrings/docker-archive-keyring.gpg
    #     echo "" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    #   when: ansible_facts['distribution'] == "Ubuntu" or ansible_facts['distribution'] == "Debian"

    - ansible.builtin.apt: 
        update_cache: yes

    - ansible.builtin.package:
        name: containerd.io
        state: present

    - name: Configure Service
      ansible.builtin.shell: |
        containerd config default > /etc/containerd/config.toml
        sed -i 's|SystemdCgroup = false|SystemdCgroup = true|g' /etc/containerd/config.toml

    - name: Service Started
      service:
        name: containerd
        state: started
        enabled: yes